allowBuilds:
  esbuild: true
  inotify: true
  sharp: true
ignoredBuiltDependencies:
  - puppeteer
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
overrides:
  path-to-regexp: '>=8.4.0'
  '@vercel/routing-utils>path-to-regexp': 6.3.0
  picomatch: '>=4.0.4'
